// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlIUgmIc44VFrwpG6ZszMYvCpiKp8VKw',
    appId: '1:1066885023316:web:8786d44f917027b3a14fc1',
    messagingSenderId: '1066885023316',
    projectId: 'mysosialapp-870c6',
    authDomain: 'mysosialapp-870c6.firebaseapp.com',
    storageBucket: 'mysosialapp-870c6.firebasestorage.app',
    measurementId: 'G-NCKBEVSM66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4l7UW2xyO8gwAJU9ckk7wfuMITN4j8z8',
    appId: '1:1066885023316:android:b9e43948432b5061a14fc1',
    messagingSenderId: '1066885023316',
    projectId: 'mysosialapp-870c6',
    storageBucket: 'mysosialapp-870c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5I_kzu_0TfxSjoy6_XpL27WW5pjfhy8',
    appId: '1:1066885023316:ios:e73ee810c15497caa14fc1',
    messagingSenderId: '1066885023316',
    projectId: 'mysosialapp-870c6',
    storageBucket: 'mysosialapp-870c6.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5I_kzu_0TfxSjoy6_XpL27WW5pjfhy8',
    appId: '1:1066885023316:ios:e73ee810c15497caa14fc1',
    messagingSenderId: '1066885023316',
    projectId: 'mysosialapp-870c6',
    storageBucket: 'mysosialapp-870c6.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUlIUgmIc44VFrwpG6ZszMYvCpiKp8VKw',
    appId: '1:1066885023316:web:9474db754267bf3ba14fc1',
    messagingSenderId: '1066885023316',
    projectId: 'mysosialapp-870c6',
    authDomain: 'mysosialapp-870c6.firebaseapp.com',
    storageBucket: 'mysosialapp-870c6.firebasestorage.app',
    measurementId: 'G-721SHLSXWX',
  );
}
